package com.rentalshop.backend.security;

import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.InterceptorRegistry;
import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

import java.nio.file.Paths;

@Configuration
@RequiredArgsConstructor
public class WebMvcConfig implements WebMvcConfigurer {

    private final DeviceAuthInterceptor deviceAuthInterceptor;

    // Not part of the Lombok-generated constructor (non-final) -- Spring
    // field-injects this normally after construction, since @Value on a
    // constructor parameter generated by @RequiredArgsConstructor wouldn't
    // be picked up (Lombok doesn't copy field annotations to the ctor param
    // by default).
    @Value("${app.storage.local.dir:./uploads}")
    private String localStorageDir;

    @Override
    public void addInterceptors(InterceptorRegistry registry) {
        registry.addInterceptor(deviceAuthInterceptor)
                .addPathPatterns("/api/**")
                // A device obviously can't present a token it doesn't have yet.
                // /actuator/health is separately public by virtue of not matching
                // "/api/**" at all -- used by both the app's cold-start check and
                // the external keep-alive cron (Section 5 / 13).
                .excludePathPatterns("/api/devices/register");
    }

    /**
     * Serves back out whatever LocalDiskObjectStorageService wrote to disk
     * (app.storage.provider=local, the default). A no-op path when running
     * against S3-compatible storage instead -- nothing ever gets written
     * under localStorageDir in that mode, so this handler just never serves
     * anything.
     */
    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        String location = "file:" + Paths.get(localStorageDir).toAbsolutePath().normalize() + "/";
        registry.addResourceHandler("/uploads/**").addResourceLocations(location);
    }
}
