package com.rentalshop.backend.service.storage;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.Objects;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Service;

import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;

/**
 * Storage backend for ImageKit's free tier (20GB storage / 20GB bandwidth
 * per month at time of writing -- comfortably enough for a small rental
 * shop's product photos). No SDK dependency: this talks to ImageKit's
 * plain REST API over {@link HttpClient}, since the two calls it needs
 * (upload, delete) are simple enough that pulling in a whole SDK jar
 * (another unverified Maven Central version, like the S3 SDK) isn't worth it.
 *
 * Activate with:
 *   app.storage.provider=imagekit
 *   app.storage.imagekit.private-key=private_xxxxxxxxxxxx      (Developer options -> API Keys, NEVER the public key)
 *   app.storage.imagekit.url-endpoint=https://ik.imagekit.io/your_imagekit_id
 *
 * Design notes:
 * <ul>
 *   <li>Upload sends {@code useUniqueFileName=false} and {@code overwriteFile=true},
 *       and splits the storage {@code key} (e.g. "items/DRESS-001/3f2a1c.webp")
 *       into ImageKit's {@code folder} ("/items/DRESS-001") and {@code fileName}
 *       ("3f2a1c.webp") params. Because the UUID-based keys generated by
 *       ItemImageService are already unique, there's no collision risk in
 *       disabling ImageKit's own uniquification -- and disabling it is what
 *       keeps {@link #publicUrl(String)} a pure, deterministic function of
 *       {@code key} (urlEndpoint + "/" + key), exactly like the local and s3
 *       backends. No response body needs to be parsed or persisted on upload.</li>
 *   <li>Delete is the one place this diverges from local/s3: ImageKit's delete
 *       endpoint takes a {@code fileId}, not a path, and this app deliberately
 *       stores only the {@code key} (schema.sql's item_images.image_url), not
 *       ImageKit's internal id -- so delete first resolves {@code key} to a
 *       {@code fileId} via ImageKit's list/search API, then deletes that id.
 *       That's one extra HTTP round-trip per delete, which is fine: deletes
 *       are rare (an admin removing a bad photo), never on a hot path.</li>
 * </ul>
 */
@Service
@ConditionalOnProperty(prefix = "app.storage", name = "provider", havingValue = "imagekit")
public class ImageKitObjectStorageService implements ObjectStorageService {

    private static final String UPLOAD_URL = "https://upload.imagekit.io/api/v1/files/upload";
    private static final String FILES_API_BASE = "https://api.imagekit.io/v1/files";

    private final HttpClient httpClient;
    private final ObjectMapper objectMapper;
    private final String privateKey;
    private final String urlEndpoint;
    private final String authHeader;
@Autowired
    public ImageKitObjectStorageService(
            @Value("${app.storage.imagekit.private-key}") String privateKey,
            @Value("${app.storage.imagekit.url-endpoint}") String urlEndpoint) {
        this(HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(15)).build(),
                new ObjectMapper(), privateKey, urlEndpoint);
    }

    /** Package-private, used by tests to inject a mock HttpClient. */
    ImageKitObjectStorageService(HttpClient httpClient, ObjectMapper objectMapper,
                                  String privateKey, String urlEndpoint) {
        if (privateKey == null || privateKey.isBlank()) {
            throw new IllegalStateException(
                    "app.storage.imagekit.private-key is required when app.storage.provider=imagekit "
                            + "(Developer options -> API Keys -> Private Key in the ImageKit dashboard; "
                            + "never the public key, that one can't authenticate server-side calls).");
        }
        if (urlEndpoint == null || urlEndpoint.isBlank()) {
            throw new IllegalStateException(
                    "app.storage.imagekit.url-endpoint is required when app.storage.provider=imagekit "
                            + "(Developer options -> URL endpoints in the ImageKit dashboard).");
        }
        this.httpClient = httpClient;
        this.objectMapper = objectMapper;
        this.privateKey = privateKey;
        this.urlEndpoint = urlEndpoint.endsWith("/")
                ? urlEndpoint.substring(0, urlEndpoint.length() - 1)
                : urlEndpoint;
        // ImageKit's REST API uses HTTP Basic auth: private key as username,
        // empty password. Same header value for every call, so compute once.
        this.authHeader = "Basic " + Base64.getEncoder().encodeToString(
                (this.privateKey + ":").getBytes(StandardCharsets.UTF_8));
    }

    @Override
    public void upload(String key, byte[] content, String contentType) {
        KeyParts parts = KeyParts.of(key);
        String boundary = "----RentalShopBoundary" + System.nanoTime();
        byte[] body = buildMultipartBody(boundary, parts, content, contentType);

        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(UPLOAD_URL))
                .header("Authorization", authHeader)
                .header("Content-Type", "multipart/form-data; boundary=" + boundary)
                .POST(HttpRequest.BodyPublishers.ofByteArray(body))
                .build();

        HttpResponse<String> response = send(request);
        if (response.statusCode() / 100 != 2) {
            throw new IllegalStateException(
                    "ImageKit upload failed for key '" + key + "': HTTP " + response.statusCode()
                            + " - " + response.body());
        }
    }

    @Override
    public void delete(String key) {
        findFileId(key).ifPresent(fileId -> {
            HttpRequest request = HttpRequest.newBuilder()
                    .uri(URI.create(FILES_API_BASE + "/" + fileId))
                    .header("Authorization", authHeader)
                    .DELETE()
                    .build();
            HttpResponse<String> response = send(request);
            // 204 = deleted, 404 = already gone -- both fine, matches the
            // "safe to call on a key that no longer exists" interface contract.
            if (response.statusCode() != 204 && response.statusCode() != 404) {
                throw new IllegalStateException(
                        "ImageKit delete failed for key '" + key + "' (fileId " + fileId + "): HTTP "
                                + response.statusCode() + " - " + response.body());
            }
        });
    }

    @Override
    public String publicUrl(String key) {
        return urlEndpoint + "/" + key;
    }

    /**
     * Resolves a storage key to ImageKit's internal fileId by listing the
     * exact folder and filtering to the exact filename. Returns empty if
     * nothing matches (already deleted, or never uploaded).
     */
    private java.util.Optional<String> findFileId(String key) {
        KeyParts parts = KeyParts.of(key);
        String searchQuery = "name=" + urlEncode("\"" + parts.fileName() + "\"");
        String url = FILES_API_BASE + "?path=" + urlEncode(parts.folder())
                + "&searchQuery=" + searchQuery + "&limit=1";

        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(url))
                .header("Authorization", authHeader)
                .GET()
                .build();
        HttpResponse<String> response = send(request);
        if (response.statusCode() != 200) {
            throw new IllegalStateException(
                    "ImageKit file lookup failed for key '" + key + "': HTTP " + response.statusCode()
                            + " - " + response.body());
        }
        JsonNode results = objectMapper.readTree(response.body());
		if (results.isArray() && !results.isEmpty()) {
		    JsonNode fileId = results.get(0).get("fileId");
		    if (fileId != null && !fileId.isNull()) {
		        return java.util.Optional.of(fileId.asText());
		    }
		}
        return java.util.Optional.empty();
    }

    private HttpResponse<String> send(HttpRequest request) {
        try {
            return httpClient.send(request, HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8));
        } catch (IOException e) {
            throw new UncheckedIOException("ImageKit request failed: " + request.uri(), e);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new IllegalStateException("ImageKit request interrupted: " + request.uri(), e);
        }
    }

    private static byte[] buildMultipartBody(String boundary, KeyParts parts, byte[] content, String contentType) {
        String lineBreak = "\r\n";
        List<byte[]> chunks = new ArrayList<>();

        chunks.add(textPart(boundary, "fileName", parts.fileName()));
        chunks.add(textPart(boundary, "folder", parts.folder()));
        chunks.add(textPart(boundary, "useUniqueFileName", "false"));
        chunks.add(textPart(boundary, "overwriteFile", "true"));

        StringBuilder fileHeader = new StringBuilder();
        fileHeader.append("--").append(boundary).append(lineBreak);
        fileHeader.append("Content-Disposition: form-data; name=\"file\"; filename=\"")
                .append(parts.fileName()).append('"').append(lineBreak);
        fileHeader.append("Content-Type: ")
                .append(contentType != null ? contentType : "application/octet-stream")
                .append(lineBreak).append(lineBreak);
        chunks.add(fileHeader.toString().getBytes(StandardCharsets.UTF_8));
        chunks.add(content);
        chunks.add(lineBreak.getBytes(StandardCharsets.UTF_8));

        chunks.add(("--" + boundary + "--" + lineBreak).getBytes(StandardCharsets.UTF_8));

        int total = chunks.stream().mapToInt(c -> c.length).sum();
        byte[] result = new byte[total];
        int pos = 0;
        for (byte[] chunk : chunks) {
            System.arraycopy(chunk, 0, result, pos, chunk.length);
            pos += chunk.length;
        }
        return result;
    }

    private static byte[] textPart(String boundary, String name, String value) {
        String part = "--" + boundary + "\r\n"
                + "Content-Disposition: form-data; name=\"" + name + "\"\r\n\r\n"
                + value + "\r\n";
        return part.getBytes(StandardCharsets.UTF_8);
    }

    private static String urlEncode(String value) {
        return URLEncoder.encode(value, StandardCharsets.UTF_8);
    }

    /** Splits a storage key like "items/DRESS-001/abc.webp" into ImageKit's folder + fileName params. */
    private record KeyParts(String folder, String fileName) {
        static KeyParts of(String key) {
            Objects.requireNonNull(key, "key must not be null");
            int lastSlash = key.lastIndexOf('/');
            if (lastSlash < 0) {
                return new KeyParts("/", key);
            }
            String dir = key.substring(0, lastSlash);
            String name = key.substring(lastSlash + 1);
            return new KeyParts("/" + dir, name);
        }
    }
}
